import { colors } from "@/styles/colors";
import { IconBuildingStore, IconBulb, IconBus, IconDroplet, IconLeaf, IconPaperBag, IconPlant, IconPlug, IconRecycle, IconWalk, IconWash } from "@tabler/icons-react-native";

export const predefinedTasks = [
  {
    id: 1,
    name: "Ir de bike ou busão 3 vezes por semana.",
    description: "Ao término será economizado 30kg de CO₂.",
    type: "Transporte",
    icon: IconBus,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 3,
    color: colors.blue,
  },
  {
    id: 2,
    name: "Reduza seu banho para 7 minutos.",
    description: "Economize até 50 litros de água por dia.",
    type: "Estilo de Vida",
    icon: IconDroplet,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 41,
    color: colors.blue,
  },
  {
    id: 3,
    name: "Leve garrafa reutilizável todos os dias.",
    description: "Evite o uso de até 30 garrafas plásticas por mês.",
    type: "Consumo",
    icon: IconRecycle,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 30,
    color: colors.orange,
  },
  {
    id: 4,
    name: "Caminhe ao invés de dirigir 2x essa semana.",
    description: "Reduza sua pegada de carbono em 10kg por semana.",
    type: "Transporte",
    icon: IconWalk,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 2,
    color: colors.yellow,
  },
  {
    id: 5,
    name: "Separe o lixo reciclável todos os dias.",
    description: "Reduza o envio de 10kg de resíduos para aterros por mês.",
    type: "Consumo",
    icon: IconRecycle,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 41,
    color: colors.cyan,
  },
  {
    id: 6,
    name: "Troque carne por vegetais no jantar 3 vezes por semana.",
    description: "Reduza 15kg de CO₂ por semana com essa prática.",
    type: "Alimentação",
    icon: IconLeaf,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 3,
    color: colors.green,
  },
  {
    id: 7,
    name: "Desligue as luzes ao sair do cômodo todos os dias.",
    description: "Economize até 15kWh de energia por mês.",
    type: "Estilo de Vida",
    icon: IconBulb,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 41,
    color: colors.yellow,
  },
  {
    id: 8,
    name: "Lave roupas apenas quando a máquina estiver cheia.",
    description: "Economize até 50 litros de água por lavagem.",
    type: "Consumo",
    icon: IconWash,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 41,
    color: colors.blue,
  },
  {
    id: 9,
    name: "Plante uma árvore durante este mês.",
    description: "Uma árvore pode absorver até 20kg de CO₂ por ano.",
    type: "Estilo de Vida",
    icon: IconPlant,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 1,
    color: colors.green,
  },
  {
    id: 10,
    name: "Evite usar sacolas plásticas durante compras semanais.",
    description: "Reduza o descarte de até 15 sacolas plásticas por mês.",
    type: "Consumo",
    icon: IconPaperBag,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 41,
    color: colors.orange,
  },
  {
    id: 11,
    name: "Desconecte aparelhos da tomada quando não estiver usando.",
    description: "Economize até 10% na conta de energia por mês.",
    type: "Estilo de Vida",
    icon: IconPlug,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 41,
    color: colors.yellow,
  },
  {
    id: 12,
    name: "Faça 4 compras em 1 em feiras durante 1 mês.",
    description: "Reduza até 5kg de CO₂ relacionado ao transporte de alimentos.",
    type: "Alimentação",
    icon: IconBuildingStore,
    progress: 0,
    isDayle: true,
    doneToday: false,
    maxProgress: 4,
    color: colors.green,
  },
]; 